#!/bin/sh

xset +dpms &
xset dpms 0 0 600 &
xset s 600 600 &
# xrdb -merge ~/.config/Xresources &
# /usr/bin/start-pulseaudio-x11 &

# compton --config ~/.config/compton/compton.conf &

# redshift &
xsetroot -cursor_name left_ptr
# synclient TouchpadOff=1 &
setxkbmap -layout "pl(intl)" \
    -option "caps:swapescape" \
    -option "terminate:ctrl_alt_bksp" &
