#!/bin/sh

export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_CACHE_HOME="$HOME/.cache"

# xset +fp /home/silencer/.fonts/tamsynmod &
# (sleep 1 && xset fp rehash) &
xset +dpms &
xset dpms 0 0 300 &
xset s 300 300 &
# xrdb -merge ~/.config/Xresources &

(sleep 5 && SpiderOak \--headless) &

redshift &
synclient TouchpadOff=1 &
setxkbmap -layout "pl(intl)" \
    -option "caps:swapescape" \
    -option "terminate:ctrl_alt_bksp" &
