#!/bin/sh

export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_CACHE_HOME="$HOME/.cache"

# xset +fp /home/silencer/.fonts/tamsynmod &
# (sleep 1 && xset fp rehash) &
xset +dpms &
xset dpms 0 0 600 &
xset s 600 600 &
xrdb -merge ~/.config/Xresources &
# /usr/bin/start-pulseaudio-x11 &

# (sleep 5 && SpiderOak \--headless) &
# (sleep 5 && SpiderOak) &

compton --config ~/.config/compton/compton.conf &

# redshift &
xsetroot -cursor_name left_ptr
synclient TouchpadOff=1 &
setxkbmap -layout "pl(intl)" \
    -option "caps:swapescape" \
    -option "terminate:ctrl_alt_bksp" &

# exec xmonad
