#!/bin/sh

if [ $(setxkbmap -print -verbose 10 | awk '/layout/ {print $NF }') == "pl(intl)" ]; then
    setxkbmap -layout "carpalx-pl_in(qgmlwy)" -option "caps:escape"
else
    setxkbmap -layout "pl(intl)" -option "caps:escape"
fi
